spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            #?? ? ???? ?????? URI
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            #OAuth2 ?? ?? ??
            authorization-grant-type: authorization_code
            #??????? ??? ??? ??? ? ?? ??.
            scope:
              - name
              - email
              - profile_image
            #?????? ??
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post\
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao

        provider:
          naver:
            #???? Naver ???? ???? ??? ? ??????? URL
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            #?? ??? ??? ???? ???? ?? URL
            token-uri: https://nid.naver.com/oauth2.0/token
            #??? ??? ???? ??? ??? ???? URL
            user-info-uri: https://openapi.naver.com/v1/nid/me
            #Naver API? ??? ??? 'response' ?? ?? ????? ??
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    root: debug